services:
  app:
    build: .
    image: developer_tools
    container_name: developer_tools_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

    restart: unless-stopped
#docker stop developer_tools_app